# Generated by Django 5.1.6 on 2025-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogYazisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("icerik", models.TextField()),
                ("yazar", models.CharField(max_length=100)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog Yazısı",
                "verbose_name_plural": "Blog Yazıları",
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
    ]
